/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function computeFullPipelineAsync(path: string, zstdLevel?: number | undefined | null, maxDemoTicks?: number | undefined | null): Promise<unknown>
export interface VoiceData {
  tick: number
  data: Buffer
  steamid: string
}
export function parseVoice(pathOrBuf: string | Buffer): Array<VoiceData>
export function listGameEvents(pathOrBuf: string | Buffer): any
/**
 * extra: lets you add new fields to grenades. Use list_updated_fields for a full list.
 * grenades: lets you disable non-projectile grenades. This can have a big difference on memory/speed.
 */
export function parseGrenades(pathOrBuf: string | Buffer, extra?: Array<string> | undefined | null, grenades?: boolean | undefined | null): any
export function parseHeader(pathOrBuf: string | Buffer): any
export function parseEvent(pathOrBuf: string | Buffer, eventName: string, playerExtra?: Array<string> | undefined | null, otherExtra?: Array<string> | undefined | null, gameEventListBytes?: Buffer | undefined | null): any
export function parseEvents(pathOrBuf: string | Buffer, eventNames?: Array<string> | undefined | null, playerExtra?: Array<string> | undefined | null, otherExtra?: Array<string> | undefined | null, gameEventListBytes?: Buffer | undefined | null): any
export function parseTicks(pathOrBuf: string | Buffer, wantedProps: Array<string>, wantedTicks?: Array<number> | undefined | null, wantedPlayers?: Array<string> | undefined | null, structOfArrays?: boolean | undefined | null, orderBySteamid?: boolean | undefined | null, propStates?: Array<WantedPropState> | undefined | null): any
/**
 * ADR-007 §VI.2 parity-debug ONLY: identical to `parse_ticks` but forces
 * `ParsingMode::ForceSingleThreaded` -- used to isolate whether a Rust-streaming-vs-JS-bulk
 * mismatch is a real codec bug or an artifact of comparing ST (streaming) against MT (bulk's
 * default ParsingMode::Normal, which resolves to multi-threaded for most prop sets).
 */
export function parseTicksForceSt(pathOrBuf: string | Buffer, wantedProps: Array<string>): any
/**
 * ADR-007 Giai đoạn 3 parity-debug ONLY: like `parse_ticks` but forces
 * `ParsingMode::ForceSingleThreaded` AND honors `wanted_ticks` (the sampled subset). Mirrors the
 * full-pipeline's internal `run_parse_ticks_raw` exactly, so a TS `computeMatchData` baseline can
 * be fed the SAME ST sampled ticks the Rust pipeline uses -> replay-chunk/stats parity is
 * apples-to-apples (not ST-pipeline vs MT-default-bulk). Prop_infos sorted by prop_name to match.
 */
export function parseTicksSampledSt(pathOrBuf: string | Buffer, wantedProps: Array<string>, wantedTicks: Array<number>, structOfArrays?: boolean | undefined | null): any
/**
 * ADR-007 §VI.2 streaming prototype (cs2-analytics): per-round variant of `parse_ticks`.
 * Instead of returning one bulk result, invokes `callback` once per round with
 * `{ tick, rows, events, bytes }` -- `bytes` is that round's actual columnar prop data
 * (reusing the same `OutputSerdeHelperStruct`/SoA serialization `parse_ticks` already uses,
 * just JSON-encoded rather than zstd -- the real columnar+quantize+zstd codec lives in
 * TS/`packages/shared` and is already parity-verified separately; JSON here is only to put a
 * REAL per-round byte payload across the N-API boundary instead of a 3-number summary) --
 * then drops that round's decoded props/events immediately after. Forces single-threaded
 * second pass (see ADR-007 for why streaming requires it: the default multi-threaded path
 * parallelizes across demo segments with no sequential round boundary). Runs synchronously on
 * the calling JS thread (same blocking behavior as `parse_ticks` today) -- not yet using a
 * threadsafe_function/background thread, since the goal here is only to validate that the
 * callback path + RAM behavior hold up from Node, not to make it async.
 */
export function parseTicksStreaming(pathOrBuf: string | Buffer, wantedProps: Array<string>, callback: (...args: any[]) => any): any
/**
 * ADR-007 §VI.2 follow-up: does the ~150MB Node/V8 overhead go away if the round payload never
 * crosses N-API as a `Buffer` at all? Same encode as `parse_ticks_streaming`, but each round's
 * bytes are written straight to `out_path` from Rust (plain `std::fs::File`, appended); the JS
 * callback -- still invoked once per round, since the round-boundary/manifest bookkeeping is
 * the interesting part to keep -- only receives numbers (tick/rows/events/offset/len), never a
 * Buffer. No `env.create_object()`+`Buffer::from()` per round, so nothing round-sized should be
 * left for V8's GC to reclaim.
 */
export function parseTicksStreamingToFile(pathOrBuf: string | Buffer, wantedProps: Array<string>, outPath: string, callback: (...args: any[]) => any): any
export function parsePlayerInfo(pathOrBuf: string | Buffer): any
export function parsePlayerSkins(pathOrBuf: string | Buffer): any
export function computeEvents(allEvents: any, grenadeRows: any, zstdLevel?: number | undefined | null): object
export function computeStats(killsBatch: any, weaponFireBatch: any, hurtBatch: any, rawKills: any, rawHurt: any, playerInfo: any, tickData: any, rounds: any): any
export function computeAimStats(killEvents: any, weaponFireBatch: any, aimTickRows: any): any
export function listUpdatedFields(pathOrBuf: string | Buffer): any
export declare class JsVariant { }
export declare class WantedPropState {
  prop: string
  state: JsVariant
}
